image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose
  - docker-compose build

stages:
  - tests


tests:
  stage: tests
  script:
    - docker-compose run --rm api  curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter && chmod +x ./cc-test-reporter && ./cc-test-reporter before-build && npm run test:coverage && ./cc-test-reporter after-build --exit-code $CODECLIMATE_ID
