image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose
  - docker-compose build

stages:
  - tests
  - deploy


tests:
  stage: tests
  script:
    - docker-compose run --rm api npm run test:coverage


deploy-production:
  stage: deploy
  only:
    - continuous-deployment
  tags:
    - prod
  script:
    - sudo docker-compose build --no-cache api
    - sudo docker-compose up -d --force-recreate --remove-orphans api
