image: docker/compose:1.24.1

services:
  - docker:dind

before_script:
  - docker-compose build

stages:
  - tests


tests:
  stage: tests
  script:
    - docker-compose run --rm api npm run test:coverage