version: "3.5"

services:
  nginx:
    image: nginx:1.15-alpine
    depends_on:
        - api
    restart: unless-stopped
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - backend

  api:
    image: $CONTAINER_TEST_IMAGE
    depends_on:
      - postgresql
    command: npm run dev
    ports:
       - "3000:3000"
    volumes:
      - .:/home/node/app:z
      - /home/node/app/node_modules
    env_file: .env
    networks:
      - backend

  postgresql:
    image: postgres:10.1-alpine
    env_file: .env
    networks:
      - backend
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data:z

networks:
  backend:
      driver: bridge
volumes:
  pgdata: