version: "3.5"

services:
  api:
    image: $CONTAINER_RELEASE_IMAGE
    depends_on:
      - postgresql
    command: npm run dev
    ports:
       - "3000:3000"
    env_file: .env
    networks:
      - backend

  postgresql:
    image: postgres:10.1-alpine
    env_file: .env
    networks:
      - backend
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data:z

networks:
  backend:
      driver: bridge
volumes:
  pgdata: